### PR TITLE
Update lawbotHQ_palette_4amla_1_a.rgb

### PR DESCRIPTION
**Pull request by yippie2020**
Inverted the rgb on the left, so the texture actually appears on the scale.

### CODE REVIEW

**Comment by toonjoey** [comment]
Just a note, you accidentally overwrote the rgb with something else. Once you correct it I'll happily merge, though.
Original
lawbotHQ_palette_4amla_1_a original
Yours
lawbotHQ_palette_4amla_1_a

**Comment by toonjoey** [comment]
Oh yeah by the way, it'd be helpful to provide a comparison with your changes. No pressure though.

**Comment by MrCheeze446** [comment]
I'm pretty sure those are two different files

**Comment by yippie2020** [comment]
My change should be accurate. I believe you're looking at lawbotHQ**Ext** instead of just lawbotHQ. No worries though, My change was a bit lazy and should have whited out the entire left side anyways. Update incoming.
Here's the comparison image as well.
scale

**Pull request merged**
